<div class="form-box" id="login-box">
    <img src="<?=$this->baseUrl('img/logoSPIE.png')?>" alt="SPIE POLSKA" width="340" />
            <div class="header">Zmień hasło</div>
    <form action="" method="post">
        <div class="body bg-gray">
            <?php echo $this->form->password; ?>
            <?php echo $this->form->repeat_password; ?>
        </div>
        <div class="footer">                                                               
            <button type="submit" class="btn bg-olive btn-block">Zmień hasło</button>  
            <p><a href="<?php
                  echo $this->url(array(
                    'action' => 'login',
                    'controller' => 'auth',
                  ));
                  ?>">Powrót</a></p>
        </div>
    </form>
</div>