<div class="form-box" id="login-box">
    <img src="<?=$this->baseUrl('img/logoSPIE.png')?>" alt="SPIE POLSKA" width="340" />
            <div class="header">Zmień hasło</div>
    <form action="<?php
    echo $this->url(
      array(
        'controller' => 'auth',
        'action' => 'forgotpassword',
        'module' => 'default'
      )
    );
    ?>" method="post">
        <div class="body bg-gray">
            <input type="text" name="email" id="email" value="" class="form-control" placeholder="Adres e-mail">
        </div>
        <div class="footer">                                                               
            <button type="submit" class="btn bg-olive btn-block">Zmień hasło</button>  
            <p><a href="<?php
                  echo $this->url(array(
                    'action' => 'login',
                    'controller' => 'auth',
                  ));
                  ?>">Powrót</a></p>
        </div>
    </form>
</div>