<?php echo $this->doctype() ?>

<html>
    <head>
        <meta charset="UTF-8">
        <title>SUDOKU GAME</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
                
        <link href="<?=$this->baseUrl('/css/app/style.css')?>" rel="stylesheet" type="text/css" />
        
    </head>
    <body>
        <div id="container">
            
        
        <div id="header">
            <div id="auth-info">
                <?php if(isset($this->layout()->user)): ?>
                    Zalogowany użytkownik: <?php echo $this->layout()->user->email; ?>
                <?php else: ?>
                    użytkownik niezalogowany
                <?php endif; ?>
            </div>
            <div id="logo">
                <a href="/">
                    <img src="<?=$this->baseUrl('/images/logo.png')?>" alt="Logo Sudoku"/>
                </a>
            </div>
            <div id="logout-button">
                <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout')); ?>">{{i18n}logout{i18n}}</a>
            </div>
        </div>
        <div style="clear: both"></div>
        <?php echo $this->layout()->content; ?>
            
        </div>
            
        <!-- scripts -->
        <script src="<?=$this->baseUrl('/js/jquery-1.10.1.min.js')?>" type="text/javascript"></script>
        <?php if(!empty($this->layout()->scripts) && is_array($this->layout()->scripts)): ?>
        <?php foreach($this->layout()->scripts as $script): ?>
        <script src="<?=$this->baseUrl($script)?>" type="text/javascript"></script>
        <?php endforeach; ?>
        <?php endif; ?>
        <?php if(!empty($this->layout()->scripts_src) && is_array($this->layout()->scripts_src)): ?>
        <script type="text/javascript">
        <?php foreach($this->layout()->scripts_src as $script): ?>
        <?php echo $script; ?>
        <?php endforeach; ?>
        </script>
        <?php endif; ?>
    </body>
</html>