<?php echo $this->doctype() ?>

<html>
    <head>
        <meta charset="UTF-8">
        <title>SUDOKU GAME</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- bootstrap 3.0.2 -->
        <link href="<?=$this->baseUrl('/css/bootstrap.min.css')?>" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="<?=$this->baseUrl('/css/font-awesome.min.css')?>" rel="stylesheet" type="text/css" />
        <!-- Ionicons -->
        <link href="<?=$this->baseUrl('/css/ionicons.min.css')?>" rel="stylesheet" type="text/css" />
        
    </head>
    <body>
        
        <script src="<?=$this->baseUrl('/js/jquery-1.10.1.min.js')?>"></script>
    </body>
</html>